version: '3'
services:
  jenkins-agent:
    build:
      context: .
      dockerfile: Dockerfile-agent
    container_name: jenkins-agent
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - jenkins-agent-data:/home/jenkins/agent
    networks:
      - jenkins
    user: root
    command: >
      /bin/bash -c "
        apt-get update && apt-get install -y curl &&
        cd /home/jenkins/agent &&
        echo '647e04c3154c54609176a9aa306b48b028005f0fcb86beeabde85cb8bda64809' > secret-file &&
        chown -R jenkins:jenkins /home/jenkins/agent &&
        curl -sO http://172.18.0.2:8080/jnlpJars/agent.jar &&
        su jenkins -c 'java -jar /home/jenkins/agent/agent.jar -url http://172.18.0.2:8080/ -secret @secret-file -name "docker-agent" -webSocket -workDir "/home/jenkins/agent"'
      "

networks:
  jenkins:
    external: true

volumes:
  jenkins-agent-data:
