version: '3.8'

services:
  auth-service:
    build:
      context: .
      dockerfile: auth-service/Dockerfile
    ports:
      - "8001:8001"
    environment:
      - JWT_SECRET_KEY=your-secret-key-change-in-production
    networks:
      - luxe-network

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - AUTH_SERVICE_URL=http://auth-service:8001
    networks:
      - luxe-network
    depends_on:
      - auth-service

  frontend:
    build: ./jewelry-store
    ports:
      - "3000:80"
    environment:
      - REACT_APP_API_BASE_URL=http://localhost:8000/api
      - REACT_APP_AUTH_BASE_URL=http://localhost:8001/auth
      - REACT_APP_BACKEND_HOST=localhost
      - REACT_APP_BACKEND_PORT=8000
    depends_on:
      - auth-service
      - backend
    networks:
      - luxe-network

networks:
  luxe-network:
    driver: bridge
