{{- if .Values.authService.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.authService.name }}
  namespace: {{ .Values.global.namespace }}
  labels:
    app: {{ .Values.authService.name }}
    version: {{ .Values.authService.image.tag | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
spec:
  replicas: {{ .Values.authService.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.authService.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.authService.name }}
        version: {{ .Values.authService.image.tag | quote }}
    spec:
      containers:
      - name: {{ .Values.authService.name }}
        image: "{{ .Values.authService.image.repository }}:{{ .Values.authService.image.tag }}"
        imagePullPolicy: {{ .Values.authService.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.authService.service.targetPort }}
          protocol: TCP
        env:
        {{- range .Values.authService.env }}
        - name: {{ .name }}
          value: {{ .value | quote }}
        {{- end }}
        {{- if .Values.authService.jwtSecretRef }}
        - name: JWT_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: {{ .Values.authService.jwtSecretRef.secretName }}
              key: {{ .Values.authService.jwtSecretRef.key }}
        {{- end }}
        envFrom:
        - configMapRef:
            name: luxe-jewelry-config
        resources:
          {{- toYaml .Values.authService.resources | nindent 10 }}
        {{- with .Values.authService.healthProbes }}
        livenessProbe:
          httpGet:
            path: {{ .liveness.path }}
            port: {{ .liveness.port }}
          initialDelaySeconds: {{ .liveness.initialDelaySeconds }}
          periodSeconds: {{ .liveness.periodSeconds }}
        readinessProbe:
          httpGet:
            path: {{ .readiness.path }}
            port: {{ .readiness.port }}
          initialDelaySeconds: {{ .readiness.initialDelaySeconds }}
          periodSeconds: {{ .readiness.periodSeconds }}
        {{- end }}
      imagePullSecrets:
      {{- range .Values.imagePullSecrets }}
      - name: {{ .name }}
      {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.authService.name }}
  namespace: {{ .Values.global.namespace }}
  labels:
    app: {{ .Values.authService.name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.authService.service.type }}
  ports:
  - port: {{ .Values.authService.service.port }}
    targetPort: {{ .Values.authService.service.targetPort }}
    protocol: TCP
  selector:
    app: {{ .Values.authService.name }}
{{- end }}
