{{- if .Values.dockerRegistry.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: docker-registry-secret
  namespace: {{ .Values.global.namespace }}
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ printf "{\"auths\":{\"%s\":{\"username\":\"%s\",\"password\":\"%s\",\"email\":\"%s\",\"auth\":\"%s\"}}}" .Values.dockerRegistry.server .Values.dockerRegistry.username .Values.dockerRegistry.password .Values.dockerRegistry.email (printf "%s:%s" .Values.dockerRegistry.username .Values.dockerRegistry.password | b64enc) | b64enc }}
{{- end }}
