{{- if .Values.jwtSecret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.jwtSecret.name }}
  namespace: {{ .Values.global.namespace }}
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
type: Opaque
stringData:
  JWT_SECRET_KEY: {{ .Values.jwtSecret.jwtSecretKey | quote }}
{{- end }}
