apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: luxe-jewelry
  labels:
    app: auth-service
    tier: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
        tier: backend
    spec:
      imagePullSecrets:
      - name: dockerhub-secret
      containers:
      - name: auth-service
        image: idave621/luxe-jewelry-auth-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8001
          name: http
          protocol: TCP
        env:
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: luxe-jewelry-config
              key: AUTH_SERVICE_PORT
        - name: JWT_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: luxe-jewelry-secrets
              key: JWT_SECRET_KEY
        - name: PYTHONUNBUFFERED
          valueFrom:
            configMapKeyRef:
              name: luxe-jewelry-config
              key: PYTHONUNBUFFERED
        - name: PYTHONPATH
          value: "/app"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /
            port: 8001
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /
            port: 8001
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: luxe-jewelry
  labels:
    app: auth-service
spec:
  type: NodePort
  ports:
  - port: 8001
    targetPort: 8001
    nodePort: 30002
    protocol: TCP
    name: http
  selector:
    app: auth-service
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: auth-service-hpa
  namespace: luxe-jewelry
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: auth-service
  minReplicas: 2
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 50
        periodSeconds: 15
    scaleUp:
      stabilizationWindowSeconds: 0
      policies:
      - type: Percent
        value: 100
        periodSeconds: 15
      - type: Pods
        value: 2
        periodSeconds: 15
      selectPolicy: Max
