apiVersion: v2
name: luxe-jewelry-chart
description: Helm chart for Luxe Jewelry Store - Full-stack e-commerce application with Frontend, Backend, and Auth services
type: application
version: 1.0.0
appVersion: "1.0.0"

maintainers:
  - name: David
    email: david@luxe-jewelry.local

keywords:
  - ecommerce
  - jewelry
  - react
  - python
  - microservices

sources:
  - https://github.com/iDave621/Luxe-Jewelry-Store
