apiVersion: v1
kind: Secret
metadata:
  name: dockerhub-secret
  namespace: luxe-jewelry
type: kubernetes.io/dockerconfigjson
data:
  # This will be created via kubectl command with your Docker Hub credentials
  # See create-docker-secret.ps1 for the command
  .dockerconfigjson: ""
